# ▼▼▼ Automatically generated by Terra-Crust, PLEASE DON'T EDIT MANUALLY, Please edit {main template/ sub-module variables} if changes are needed :slight_smile: ▼▼▼
locals {
  tailscale = {
    atomic             = coalesce(var.tailscale.atomic, true)
    cleanup_on_fail    = coalesce(var.tailscale.cleanup_on_fail, true)
    client_id          = coalesce(var.tailscale.client_id, "ChangeIt")
    client_secret      = coalesce(var.tailscale.client_secret, "ChangeIt")
    create_namespace   = coalesce(var.tailscale.create_namespace, true)
    helm_chart_name    = coalesce(var.tailscale.helm_chart_name, "tailscale")
    helm_chart_version = coalesce(var.tailscale.helm_chart_version, "v1.66.3")
    helm_release_name  = coalesce(var.tailscale.helm_release_name, "tailscale")
    helm_repo_url      = coalesce(var.tailscale.helm_repo_url, "tailscale")
    namespace          = coalesce(var.tailscale.namespace, "tailscale")
    timeout            = coalesce(var.tailscale.timeout, 300)
    wait               = coalesce(var.tailscale.wait, true)


  }
}




