# ▼▼▼ Automatically generated by Terra-Crust, PLEASE DON'T EDIT MANUALLY, Please edit {main template/ sub-module variables} if changes are needed :slight_smile: ▼▼▼

variable "bootstrap" {
  description = <<EOT
	(Optional) bootstrap Module will be used by default.
	EOT
  type = object({
    nodes = optional(map(object({
      hostname   = string
      ip_address = string
      role       = list(string)
    })))
    private_key = optional(string)
    ssh_user    = optional(string)
  })
  default = {
    nodes       = {}
    private_key = "null"
    ssh_user    = "root"
  }
}
variable "tailscale" {
  description = <<EOT
	(Optional) tailscale Module will be used by default.
	EOT
  type = object({
    atomic             = optional(bool)
    cleanup_on_fail    = optional(bool)
    client_id          = optional(string)
    client_secret      = optional(string)
    create_namespace   = optional(bool)
    helm_chart_name    = optional(string)
    helm_chart_version = optional(string)
    helm_release_name  = optional(string)
    helm_repo_url      = optional(string)
    namespace          = optional(string)
    timeout            = optional(number)
    wait               = optional(bool)
  })
  default = {
    atomic             = true
    cleanup_on_fail    = true
    client_id          = "ChangeIt"
    client_secret      = "ChangeIt"
    create_namespace   = true
    helm_chart_name    = "tailscale"
    helm_chart_version = "v1.66.3"
    helm_release_name  = "tailscale"
    helm_repo_url      = "tailscale"
    namespace          = "tailscale"
    timeout            = 300
    wait               = true
  }
} 